# Generated by Django 5.0.2 on 2024-02-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdimmunity', '0003_remindersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindersettings',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
